{
 "title": "CF: Cell Summary",
 "tags": [
  "cf",
  "diego"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ip",
    "label": "IP",
    "query": "label_values(CapacityTotalContainers, ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cell Status",
   "type": "singlestat",
   "description": "Status of this Diego cell",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(GardenHealthCheckFailed{ip=~\"$ip\"})"
    }
   ]
  },
  {
   "title": "Remaining Containers",
   "type": "singlestat",
   "description": "Number of remaining containers in this Diego cell",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(CapacityRemainingContainers{ip=~\"$ip\"}) by(job, ip))"
    }
   ]
  },
  {
   "title": "Remaining Memory",
   "type": "singlestat",
   "description": "Remaining memory in this Diego cell",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(CapacityRemainingMemory{ip=~\"$ip\"}) by(job, ip))"
    }
   ]
  },
  {
   "title": "Remaining Disk",
   "type": "singlestat",
   "description": "Remaining disk in this Diego cell",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(CapacityRemainingDisk{ip=~\"$ip\"}) by(job, ip))"
    }
   ]
  },
  {
   "title": "Total Containers",
   "type": "graph",
   "description": "Cumulative used and available number of containers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(CapacityTotalContainers{ip=~\"$ip\"}) by(job, ip)) - sum(avg(CapacityRemainingContainers{ip=~\"$ip\"}) by(job, ip))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(avg(CapacityRemainingContainers{ip=~\"$ip\"}))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Application Instances",
   "type": "table",
   "description": "Application instances running in this Diego cell",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "avg(cpu{ip=~\"$ip\"}) by(app_id, instance_id, app_name, instance_id, organization_name, space_name)",
     "legendFormat": "{{ organization_name }} / {{ space_name }} / {{ app_name }} #{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Total Cell Memory",
   "type": "graph",
   "description": "Cumulative allocated and available MiB of memory to allocate to containers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg(CapacityTotalMemory{ip=~\"$ip\"}) by(job, ip)) - sum(avg(CapacityRemainingMemory{ip=~\"$ip\"}) by(job, ip))",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(avg(CapacityRemainingMemory{ip=~\"$ip\"}) by(job, ip))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Current Memory Usage per Application Instance",
   "type": "table",
   "description": "Current memory usage per application instance running in this Diego cell.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "min(memory{ip=~\"$ip\"}) by(app_name, instance_id, organization_name, space_name)",
     "legendFormat": "{{ organization_name }} / {{ space_name }} / {{ app_name }} #{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Total Cell Disk",
   "type": "graph",
   "description": "Cumulative allocated and available MiB of disk to allocate to containers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg(CapacityTotalDisk{ip=~\"$ip\"}) by(job, ip)) - sum(avg(CapacityRemainingDisk{ip=~\"$ip\"}) by(job, ip))",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(avg(CapacityRemainingDisk{ip=~\"$ip\"}) by(job, ip))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Current Disk Usage per Application Instance",
   "type": "table",
   "description": "Current disk usage per application instance running in this Diego cell.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "min(disk{ip=~\"$ip\"}) by(app_name, instance_id, organization_name, space_name)",
     "legendFormat": "{{ organization_name }} / {{ space_name }} / {{ app_name }} #{{ instance_id }}"
    }
   ]
  }
 ]
}