{
 "title": "CF: Cells Capacity",
 "tags": [
  "cf",
  "diego"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Number of Cells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(count(CapacityTotalContainers) by(instance))"
    }
   ]
  },
  {
   "title": "Cell with Least Remaining Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(min(CapacityRemainingMemory) by(instance))"
    }
   ]
  },
  {
   "title": "Cell with Least Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "bottomk(1, min(CapacityRemainingMemory) by(ip))",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Total Cell Memory",
   "type": "graph",
   "description": "Cumulative used and available MiB of memory to allocate to containers.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg(CapacityTotalMemory) by(job, ip)) - sum(avg(CapacityRemainingMemory) by(job, ip))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(avg(CapacityRemainingMemory) by(job, ip))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Total Cell Disk",
   "type": "graph",
   "description": "Cumulative used and available MiB of disk to allocate to containers.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg(CapacityTotalDisk) by(job, ip)) - sum(avg(CapacityRemainingDisk) by(job, ip))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(avg(CapacityRemainingDisk) by(job, ip))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Running Containers Per Cell",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(CapacityTotalContainers - CapacityRemainingContainers) by(ip)",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Memory Used Per Cell",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(avg(CapacityTotalMemory - CapacityRemainingMemory) by(ip)) / 1024",
     "legendFormat": "{{ ip }}"
    }
   ]
  }
 ]
}