{
 "title": "CF: Router",
 "tags": [
  "cf",
  "router"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Rate Requests per second",
   "type": "graph",
   "description": "Successful and failed requests received per second during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(rate(total_requests[5m])) by(job, ip))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(avg(rate(rejected_requests[5m])) by(job, ip))",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Rate Responses per second",
   "type": "graph",
   "description": "HTTP responses per second during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(rate(responses_2xx[5m])) by(job, ip))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(avg(rate(responses_3xx[5m])) by(job, ip))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(avg(rate(responses_4xx[5m])) by(job, ip))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(avg(rate(responses_5xx[5m])) by(job, ip))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "description": "Cumulative number of successful and failed requests received. Emitted every 5 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(total_requests) by(job, ip))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(avg(rejected_requests) by(job, ip))",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Total Responses",
   "type": "graph",
   "description": "Cumulative number of HTTP responses. Emitted every 5 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(responses) by(job, ip))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(avg(responses_3xx) by(job, ip))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(avg(responses_4xx) by(job, ip))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(avg(responses_5xx) by(job, ip))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Time in milliseconds that the Gorouter took to handle requests to its application endpoints. Emitted per router request.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "avg(latency) by(job, ip)", "legendFormat": "{{ job }}/{{ ip }}" }
   ]
  },
  {
   "title": "Route Lookup Time",
   "type": "graph",
   "description": "Route Lookup time.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(route_lookup_time) by(job, ip)",
     "legendFormat": "{{ job }}/{{ ip }}"
    }
   ]
  },
  {
   "title": "Rate Register Messages Received per second",
   "type": "graph",
   "description": "Route registration messages received per second during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(registry_message[5m])) by(job, ip)",
     "legendFormat": "{{ job }}/{{ ip }}"
    }
   ]
  },
  {
   "title": "Total Register Messages Received",
   "type": "graph",
   "description": "Number of route registration messages received. Emitted per route-register message.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(registry_message) by(job, ip)",
     "legendFormat": "{{ job }}/{{ ip }}"
    }
   ]
  },
  {
   "title": "Total Routes Registered",
   "type": "graph",
   "description": "Number of routes registered. Emitted every 30 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(total_routes)", "legendFormat": "Routes" }
   ]
  }
 ]
}